import { getSchoolRegistration } from "@/lib/api";
import { useSchoolRegistration } from "@/lib/mutations";
import { useGetCourse, useGetSchoolRegistration } from "@/lib/queries";
import { supabase } from "@/lib/supabase";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { useQueryClient } from "react-query";
import { QRCode } from "react-qrcode-logo";
import Flagged from "@/components/modules/flagged";
import * as htmlToImage from "html-to-image";
import download from "downloadjs";

export default function Reference() {
  const router = useRouter();
  const queryClient = useQueryClient();

  const { course_id, reference_id } = router.query;

  const { data: registration, isLoading: __registration } =
    useGetSchoolRegistration(reference_id as string);
  const { data: course, isLoading: __course } = useGetCourse(
    course_id as string
  );

  useEffect(() => {
    supabase
      .channel("table-db-changes")
      .on(
        "postgres_changes",
        {
          event: "UPDATE",
          schema: "public",
          table: "school_registrations",
          filter: "id=eq." + reference_id,
        },
        (payload) => {
          queryClient.setQueryData(
            ["getSchoolRegistration", { id: reference_id }],
            payload.new
          );
        }
      )
      .subscribe();
  }, []);

  const handleClick = () => {
    const rootEl = document.getElementById("qr");
    htmlToImage.toPng(rootEl!).then(function (dataUrl) {
      download(
        dataUrl,
        `${registration?.first_name}'s ${course?.title} Admission Reference.png`
      );
    });
  };

  return (
    <Flagged flagKey="enableSdlAdmission">
      <Head>
        <title>Disciplr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="p-7 w-screen flex flex-col">
        <header className="shrink-0 text-primary font-bold text-2xl flex flex-col gap-4">
          School of Leaders
        </header>
        <main className="grow flex justify-center items-center h-full flex-col pt-8">
          {registration?.status === "PENDING" && (
            <p className="px-8 text-center text-[#656565]">
              Hi {registration.first_name}! Your application is now in review of
              one of our admins. Please wait for the approval of your
              application in {course?.title}.{" "}
              <div className="mt-8">
                <span className="font-semibold">
                  Kindly keep this QR code as your Admission reference
                </span>
                . We will notify you once you are admitted.
              </div>
            </p>
          )}
          {registration?.status === "REJECTED" && (
            <p className="px-8 text-center text-[#656565]">
              We are sorry to hear {registration.first_name} that you are not
              able to accept you for application for {course?.title}.{" "}
              <div className="mt-8">
                <span className="font-semibold">
                  Please proceed to admission table and ask for assistance.
                </span>
              </div>
            </p>
          )}
          {registration?.status === "APPROVED" && (
            <p className="px-5   text-center text-[#656565]">
              Awesome! You have now been admitted to {course?.title}.
              <div className="mt-8">
                <span className="font-semibold">
                  Please proceed to accounting table
                </span>{" "}
                and prepare {course?.fee ?? "0.00"} pesos for the enrollment
                fee. Kindly present this QR code and proceed to payment.
              </div>
            </p>
          )}
          {registration?.status === "ENROLLED" && (
            <p className="px-8 text-center text-[#656565]">
              Congratulations {registration.first_name}! You have successfully
              enrolled for {course?.title}.{" "}
              <div className="mt-8">
                <span className="font-semibold">
                  Proceed now to admission table and verify your enrollment
                  status.
                </span>
              </div>
            </p>
          )}

          <header className="text-[#686777] text-[12px] mt-12">
            ADMISSION REFERENCE: {registration?.reference}
          </header>
          <div id="qr" className="py-3">
            <QRCode
              size={280}
              qrStyle="dots"
              logoWidth={40}
              eyeColor={"#313131"}
              fgColor="#313131"
              eyeRadius={0.5}
              value={`https://api.fishgen.org/_/${registration?.reference}`}
            />
          </div>
          <button
            onClick={handleClick}
            className="text-[#6E7AC5] text-[12px] hover:underline"
          >
            DOWNLOAD
          </button>
        </main>
      </div>
    </Flagged>
  );
}
