import { getSchoolRegistration } from "@/lib/api";
import { useSchoolRegistration } from "@/lib/mutations";
import { useGetCourse, useGetSchoolRegistration } from "@/lib/queries";
import { supabase } from "@/lib/supabase";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { useQueryClient } from "react-query";
import { QRCode } from "react-qrcode-logo";
import Flagged from "@/components/modules/flagged";

export default function Reference() {
  const router = useRouter();
  const queryClient = useQueryClient();

  const { course_id, reference_id } = router.query;

  const { data: registration, isLoading: __registration } =
    useGetSchoolRegistration(reference_id as string);
  const { data: course, isLoading: __course } = useGetCourse(
    course_id as string
  );

  console.log(registration);

  useEffect(() => {
    supabase
      .channel("table-db-changes")
      .on(
        "postgres_changes",
        {
          event: "UPDATE",
          schema: "public",
          table: "school_registrations",
          filter: "id=eq." + reference_id,
        },
        (payload) => {
          queryClient.setQueryData(
            ["getSchoolRegistration", { id: reference_id }],
            payload.new
          );
          console.log(payload.new);
        }
      )
      .subscribe();
  }, []);

  return (
    <Flagged flagKey="enableSdlAdmission">
      <Head>
        <title>Disciplr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="p-7 scanner-container w-screen flex flex-col">
        <header className="shrink-0 text-primary font-bold text-2xl flex flex-col gap-4">
          School of Leaders
        </header>
        <main className="grow flex justify-center items-center h-full flex-col">
          {/* <p className="px-12 text-center text-xl text-[#656565]">
            Waiting to be admitted in [COURSE] batch [BATCH].{" "}
            <strong>Keep this QR code as your Admission reference</strong>. We
            will notify you once you are admitted.
          </p> */}
          {/* <p className="px-12 text-center text-xl text-[#656565]">
            <strong className="text-error">We are sorry</strong> to hear that
            you are not able to accept you for application for this course.{" "}
            <strong>Please proceed to window 3 and ask for assistance.</strong>
          </p> */}
          {/* <p className="px-12 text-center text-xl text-[#656565]">
            <strong className="text-primary">You have now been admitted</strong>{" "}
            to [COURSE] batch [BATCH].{" "}
            <strong>Please proceed to Window 2</strong> and prepare for the
            enrollment fee. Kindly present this QR code and proceed to payment.
          </p> */}
          <p className="px-12 text-center text-xl text-[#656565]">
            <strong className="text-success">Congratulations!</strong> You have
            successfully enrolled for the [COURSE] batch [BATCH].{" "}
            <strong>Proceed to window 3 to verify your enrollment</strong>
          </p>
          <header className="mt-20 text-[#686777] text-[12px] uppercase">
            Admission Reference
          </header>
          <div className="py-3">
            <QRCode
              size={280}
              qrStyle="dots"
              logoWidth={40}
              eyeColor={"#313131"}
              fgColor="#313131"
              eyeRadius={0.5}
              value={`api.fishgen.org/_/${registration?.reference}`}
            />
          </div>
          <button className="text-[#6E7AC5] text-[12px] hover:underline">
            DOWNLOAD
          </button>
        </main>
      </div>
    </Flagged>
  );
}
