import { useSchoolRegistration } from "@/lib/mutations";
import { useGetCourse } from "@/lib/queries";
import Head from "next/head";
import { useRouter } from "next/router";

export default function Apply() {
  const router = useRouter();
  const { course_id } = router.query;

  const { data: course } = useGetCourse(course_id as string);
  const { mutate, isLoading } = useSchoolRegistration();

  const handleSubmit = () => {
    mutate(
      {
        course_id: course_id as string,
        first_name: "John",
      },
      {
        onSuccess(data) {
          router.push(`/sdl/admission/${course_id}/${data.id}`);
        },
      }
    );
  };

  return (
    <>
      <Head>
        <title>Disciplr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="flex flex-col p-7">
        <header className="shrink-0 text-primary font-bold text-2xl flex flex-col gap-4 mb-12">
          School of Leaders
        </header>
        <div className="mb-7 text-xl">
          Registration form for <strong>{course?.title}</strong>
        </div>
        <div className="flex flex-col gap-4">
          <input
            placeholder="First Name"
            className="p-4 bg-[#F9F9F9] rounded-[12px] outline-0"
          />
          <input
            placeholder="Middle Name"
            className="p-4 bg-[#F9F9F9] rounded-[12px] outline-0"
          />
          <input
            placeholder="Last Name"
            className="p-4 bg-[#F9F9F9] rounded-[12px] outline-0"
          />
          <button
            onClick={handleSubmit}
            className="bg-[#6E7AC5] text-white p-4 rounded-lg mt-7"
          >
            Submit
          </button>
        </div>
      </main>
    </>
  );
}
