import Header from "@/components/base/header";
import Layout from "@/components/templates/Layout";
import Head from "next/head";
import { useEffect } from "react";
import vhCheck from "vh-check";
import styles from "./profile.module.scss";

export default function Home() {
  useEffect(() => {
    vhCheck("main");
  }, []);

  return (
    <>
      <Head>
        <title>Disciplr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout activeRoute="profile">
        <Header>
          <div className="flex w-full justify-between items-center">
            <span>Profile</span>
            <button>
              <span className="font-normal text-base text-[#554AF0]">Edit</span>
            </button>
          </div>
        </Header>
        <div className="flex justify-center py-5">
          <div className="w-[100px] h-[100px] bg-gray-100 rounded-full" />
        </div>
        <label className={styles.label}>General Information</label>
      </Layout>
    </>
  );
}
