import Layout from "@/components/templates/page";
import { useUpdateApplication } from "@/lib/mutations";
import { useGetApplicationList, useGetCourses } from "@/lib/queries";
import { supabase } from "@/lib/supabase";
import Head from "next/head";
import { useEffect } from "react";
import { useQueryClient } from "react-query";

export default function Accounting() {
  const queryClient = useQueryClient();

  const { data: courses } = useGetCourses();
  const { data: applications } = useGetApplicationList();
  const { mutate } = useUpdateApplication();

  const handleApprove = (id?: string) => {
    mutate({
      id: id ?? (global as any)?.id,
      status: "APPROVED",
    });
  };

  const handleReject = (id: string) => {
    mutate({
      id,
      status: "REJECTED",
    });
  };

  useEffect(() => {
    supabase
      .channel("table-db-changes")
      .on(
        "postgres_changes",
        { event: "INSERT", schema: "public", table: "school_registrations" },
        (payload) => queryClient.invalidateQueries(["getApplicationList"])
      )
      .subscribe();
  }, []);

  console.log(applications);

  return (
    <>
      <Head>
        <title>Disciplr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Layout activeRoute="" isNavigationHidden>
        <main className="flex flex-col p-7 gap-3">
          <h1 className="text-4xl font-semibold">Application List</h1>
          <button onClick={() => handleApprove()}>Approve</button>
        </main>
      </Layout>
    </>
  );
}
