import Layout from "@/components/templates/page";
import { sendBulkSms } from "@/lib/api";
import { useUpdateApplication } from "@/lib/mutations";
import { useGetApplicationList, useGetCourses } from "@/lib/queries";
import { supabase } from "@/lib/supabase";
import moment from "moment";
import Head from "next/head";
import { useEffect } from "react";
import { useQueryClient } from "react-query";
import { toast } from "react-toastify";

export default function Accounting() {
  const queryClient = useQueryClient();

  const { data: courses } = useGetCourses();
  const { data: applications } = useGetApplicationList();

  useEffect(() => {
    supabase
      .channel("table-db-changes")
      .on(
        "postgres_changes",
        { event: "INSERT", schema: "public", table: "school_registrations" },
        () => queryClient.invalidateQueries(["getApplicationList"])
      )
      .subscribe();
  }, []);

  return (
    <>
      <Head>
        <title>Disciplr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Layout activeRoute="" isNavigationHidden>
        <main className="flex flex-col p-7 gap-3">
          <h1 className="text-4xl font-semibold">Application List</h1>
          {applications?.map((application) => {
            const course = courses?.find(
              (item) => item.id === application?.course_id
            );

            return (
              <div
                key={application?.id}
                className="bg-[#F9F9F9] rounded-2xl p-5"
              >
                <div className="grid grid-cols-4 gap-4">
                  <div className="col-span-1 ">
                    <div>
                      Name: {application?.first_name} {application?.middle_name}{" "}
                      {application?.last_name}
                    </div>
                    <div>Course: {course?.title}</div>
                    <div>
                      Date Enrolled:{" "}
                      {moment(application?.created_at).format("lll")}
                    </div>
                  </div>
                  <div className="col-span-1 ">
                    <div>Leader: {application?.cell_leader_name}</div>
                    <div>
                      Network Leader: {application?.network_leader_name}
                    </div>
                    <div>
                      Birthday:{" "}
                      {application?.birthday ? (
                        <>
                          {moment(application?.birthday).format(
                            "MMMM DD, YYYY"
                          )}
                        </>
                      ) : (
                        "-"
                      )}
                    </div>
                  </div>
                  <div className="col-span-1 ">
                    <div>
                      Consolidation Level: {application?.lesson_completed}
                    </div>
                    <div>OJT: {application?.ojt || "-"}</div>
                  </div>
                  <div className="col-span-1 ">
                    <div>
                      Do have cellgroup:{" "}
                      {application?.with_cellgroup ? "✅" : "❌"}
                    </div>
                    <div>
                      Want to be Admin or Teacher:{" "}
                      {application?.want_to_be_admin_or_teacher ? "✅" : "❌"}
                    </div>
                    <div>Role: {application?.role || "-"}</div>
                  </div>
                </div>
                <Actions application={application} />
              </div>
            );
          })}
        </main>
      </Layout>
    </>
  );
}

function Actions({ application }: any) {
  const { data: courses } = useGetCourses();
  const { data: applications } = useGetApplicationList();
  const { mutate, isLoading } = useUpdateApplication();

  const handleApprove = (id?: string) => {
    mutate(
      {
        id: id ?? (global as any)?.id,
        status: "APPROVED",
      },
      {
        onSuccess() {
          const application = applications?.find((item) => item.id === id);
          const course = courses?.find(
            (item) => item.id === application?.course_id
          );

          const contact_number = application?.contact_number;

          const message = `You have now been admitted to ${course?.title}. Please proceed to Window 2 and prepare ${course?.fee} for the enrollment fee. Kindly present this QR code and proceed to payment.`;
          sendBulkSms(message, [contact_number], "Disciplr");
          toast.success("Application approved 🎉");
        },
      }
    );
  };

  const handleReject = (id: string) => {
    mutate(
      {
        id,
        status: "REJECTED",
      },
      {
        onSuccess() {
          toast.success("Application rejected.");
        },
      }
    );
  };

  return (
    <>
      <div className="flex gap-2 mt-3">
        <button
          disabled={isLoading}
          onClick={() => handleApprove(application?.id)}
          className="bg-green-500 text-white text-sm px-2 py-1 rounded-lg disabled:opacity-50 disabled:cursor-not-allowed"
        >
          Approve
        </button>
        <button
          disabled={isLoading}
          onClick={() => handleReject(application?.id)}
          className="bg-red-500 text-white text-sm px-2 py-1 rounded-lg disabled:opacity-50 disabled:cursor-not-allowed"
        >
          Reject
        </button>
      </div>
    </>
  );
}
