import Header from "@/components/base/header";
import Layout from "@/components/templates/page";
import { useGetNetworkDetails } from "@/lib/queries";
import Head from "next/head";
import { useRouter } from "next/router";
import Member from "@/components/modules/networks/members/member";
import Body from "@/components/base/body";
import { Leader } from "@/components/modules/networks/leader";
import { Networks } from "@/components/modules/networks/networks";
import Addnetwork from "@/components/modules/networks/add-network";
import Link from "next/link";

const NetowrkDetails = () => {
  const router = useRouter();
  const { data: network } = useGetNetworkDetails(String(router.query.id));
  return (
    <>
      <Head>
        <title>Disciplr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Layout activeRoute="networks">
        <Header>
          <div className="flex w-full justify-between items-center">
            <span className="whitespace-nowrap overflow-hidden text-ellipsis">
              {network?.name}
            </span>
            <Link href={`/networks/${String(router.query.id)}/update`}>
              <button className="pl-4 shrink-0 text-sm font-medium text-[#6e7ac5]">
                Edit
              </button>
            </Link>
          </div>
        </Header>
        {network?.status === "Inactive" && (
          <div className="bg-orange-200 w-full left-0 text-base p-4">
            <span className="text-xs font-semibold">
              This network is Inactive.{" "}
            </span>
          </div>
        )}
        <Body>
          <div
            style={{
              opacity: network?.status === "Inactive" ? 0.7 : 1,
            }}
            className="flex flex-col gap-12"
          >
            <Leader
              first_name={network?.discipler_id.first_name}
              last_name={network?.discipler_id.last_name}
            />
            <div className="px-7 flex flex-col gap-12">
              <Member />
              <Networks id={network?.id ?? ""} />
              {network?.status === "Active" && <Addnetwork />}
              <div />
            </div>
          </div>
        </Body>
      </Layout>
    </>
  );
};

export default NetowrkDetails;
