import Header from "@/components/base/header";
import Layout from "@/components/templates/layout";
import { useGetNetworkDetails } from "@/lib/queries";
import Head from "next/head";
import { useRouter } from "next/router";
import Member from "@/components/modules/networks/members/member";
import Body from "@/components/base/body";
import { Leader } from "@/components/modules/networks/leader";
import { Networks } from "@/components/modules/networks/networks";
import Addnetwork from "@/components/modules/networks/add-network";
import { useEffect, useState } from "react";

const UpdateNetworkDetails = () => {
  const router = useRouter();
  const { data: network } = useGetNetworkDetails(String(router.query.id));

  const [name, setName] = useState("");

  useEffect(() => {
    if (network) {
      setName(network.name);
    }
  }, []);

  return (
    <>
      <Head>
        <title>Disciplr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout activeRoute="networks">
        <Header>
          <div className="flex w-full justify-between items-center">
            <span className="whitespace-nowrap overflow-hidden text-ellipsis">
              Update Network
            </span>
            <button className="pl-4 shrink-0 text-sm font-medium text-[#554AF0]">
              Save
            </button>
          </div>
        </Header>
        <Body>
          <div className="flex flex-col gap-12">
            <div>
              <div className="flex flex-col gap-2 px-7 mt-7">
                <label className="block uppercase text-sm">Network Name</label>
                <input
                  autoFocus
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  className="bg-[#f2f2f8] w-full px-4 py-3 rounded-lg outline-none"
                  placeholder="Enter Network Name"
                />
              </div>
            </div>
            <div className="px-7 flex flex-col gap-12">
              <Member />
              <Networks id={network?.id ?? ""} />
              <div />
            </div>
          </div>
        </Body>
      </Layout>
    </>
  );
};

export default UpdateNetworkDetails;
