import Layout from "@/components/templates/layout";
import Head from "next/head";
import NetorkCard from "@/components/modules/network-card";

export default function Home() {
  return (
    <>
      <Head>
        <title>Disciplr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <NetorkCard
          first_name="John"
          last_name="Doe"
          created_at="2021-01-01"
          member_count={4}
          status="Active"
        />
      </Layout>
    </>
  );
}
