import Layout from "@/components/templates/page";
import Head from "next/head";
import Header from "@/components/base/header";
import { useRouter } from "next/router";
import { useGetConsolidationById } from "@/lib/queries";

export default function LessonScreen() {
  const router = useRouter();
  const { data: lesson } = useGetConsolidationById(
    router.query.lesson as string
  );
  return (
    <>
      <Head>
        <title>Disciplr | {lesson?.lesson_code.name}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Layout activeRoute="conso">
        <Header showBackArrrow>
          <div className="flex w-full justify-between items-center">
            <span>
              {lesson?.lesson_code.name}: {lesson?.lesson_code.title}
            </span>
          </div>
        </Header>
      </Layout>
    </>
  );
}
