import Header from "@/components/base/header";
import Layout from "@/components/templates/layout";
import { useGetNetworkDetails, useGetSubNetworks } from "@/lib/queries";
import Head from "next/head";
import { useRouter } from "next/router";
import NetworkCard from "@/components/modules/network-card";
import moment from "moment";

const NetowrkDetails = () => {
  const router = useRouter();
  const { data: network } = useGetNetworkDetails(String(router.query.id));
  const { data: subNetworks } = useGetSubNetworks(network?.id ?? "");

  console.log(network);
  console.log(subNetworks);

  return (
    <>
      <Head>
        <title>Disciplr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout activeRoute="networks">
        <Header>
          <div className="flex w-full justify-between items-center">
            <span>{network?.name}</span>
          </div>
        </Header>
        <div className="p-7">
          <section>
            <header>Leader</header>
            {network?.discipler_id.first_name} {network?.discipler_id.last_name}
          </section>
          <section className="mt-12">
            <header>Networks</header>
            {subNetworks?.map((network) => {
              return (
                <NetworkCard
                  id={network.id}
                  key={network.id}
                  alias={network.name}
                  created_at={moment(network.created_at).format("MMM DD, YYYY")}
                  member_count={network.member_count}
                  status={network.status}
                />
              );
            })}
          </section>
        </div>
      </Layout>
    </>
  );
};

export default NetowrkDetails;
