import Header from "@/components/base/header";
import Layout from "@/components/templates/layout";
import { useGetNetworkDetails } from "@/lib/queries";
import Head from "next/head";
import { useRouter } from "next/router";
import Member from "@/components/modules/networks/members/member";
import Body from "@/components/base/body";
import { Leader } from "@/components/modules/networks/leader";
import { Networks } from "@/components/modules/networks/networks";
import Addnetwork from "@/components/modules/networks/add-network";

const NetowrkDetails = () => {
  const router = useRouter();
  const { data: network } = useGetNetworkDetails(String(router.query.id));
  return (
    <>
      <Head>
        <title>Disciplr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout activeRoute="networks">
        <Header>
          <div className="flex w-full justify-between items-center">
            <span>{network?.name}</span>
          </div>
        </Header>
        <Body>
          <div className="p-7 flex flex-col gap-12">
            <Leader
              first_name={network?.discipler_id.first_name}
              last_name={network?.discipler_id.last_name}
            />
            <Networks id={network?.id ?? ""} />
            <Member />
            <Addnetwork />
          </div>
        </Body>
      </Layout>
    </>
  );
};

export default NetowrkDetails;
