import Header from "@/components/base/header";
import Layout from "@/components/templates/layout";
import Head from "next/head";
import NetworkCard from "@/components/modules/network-card";
import { useGetNetworksByDiscipler, useGetProfile } from "@/lib/queries";

const Networks = () => {
  const { data: profile } = useGetProfile();
  const { data: networks } = useGetNetworksByDiscipler(profile?.id ?? "");

  console.log(networks);

  return (
    <>
      <Head>
        <title>Disciplr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout activeRoute="networks">
        <Header>
          <div className="flex w-full justify-between items-center">
            <span>Networks</span>
          </div>
        </Header>
        {networks?.map((network) => {
          return (
            <NetworkCard
              key={network.id}
              alias={network.name}
              created_at={network.created_at}
              member_count={network.member_count}
              status={network.status}
            />
          );
        })}
      </Layout>
    </>
  );
};

export default Networks;
