import Header from "@/components/base/header";
import Layout from "@/components/templates/page";
import { useGetNetworkDetails, useSearchLeaders } from "@/lib/queries";
import Head from "next/head";
import { useRouter } from "next/router";
import Body from "@/components/base/body";
import { useEffect, useRef, useState } from "react";
import Button from "@/components/base/button";
import { useOpenNetwork } from "@/lib/mutations";
import { SearchedLeader } from "@/lib/api";
import { useDebounce } from "@/lib/hooks";

const NewNetwork = () => {
  const [initialized, setInitialized] = useState(false);
  const [leaderQ, setLeaderQ] = useState("");
  const [name, setName] = useState("");
  const router = useRouter();
  const inputRef = useRef<HTMLInputElement>(null);
  const { mutate: openNetwork } = useOpenNetwork(router.query.id as string);
  const debouncedSearch = useDebounce(leaderQ, 500);
  const { data: searchResult } = useSearchLeaders(debouncedSearch);
  const [selectedLeader, setSelectedLeader] = useState<SearchedLeader | null>(
    null
  );
  const { data: network } = useGetNetworkDetails(String(router.query.id));

  useEffect(() => {
    if (network && !name && !initialized) {
      setName(`${network.discipler_id.first_name}'s Network`);
      setInitialized(true);
    }
  }, [name, network, initialized]);

  const handleOnSuccess = () => {
    router.push(`/networks/${router.query.id}`);
  };

  const handleSubmit = () => {
    if (network) {
      const payload = {
        name,
        discipler_id: selectedLeader?.id ?? "",
        network_id: network?.id,
      };

      openNetwork(payload, { onSuccess: handleOnSuccess });
    }
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setLeaderQ(e.target.value);
    setSelectedLeader(null);
  };

  const handleSelectLeader = (leader: SearchedLeader) => {
    setLeaderQ(`${leader.first_name} ${leader.last_name ?? ""}`.trim());
    setSelectedLeader(leader);
    setName(leader.first_name + "'s Network");
    inputRef.current?.focus();
  };

  return (
    <>
      <Head>
        <title>Disciplr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Layout activeRoute="networks">
        <Header>
          <div className="flex w-full justify-between items-center">
            New Network
          </div>
        </Header>
        <Body>
          <div className="p-7 flex flex-col gap-3">
            <div className="flex flex-col gap-2">
              <label className="block uppercase text-sm">
                Leader&apos;s Name
              </label>
              <input
                placeholder="Search leader"
                value={leaderQ}
                onChange={handleChange}
                className="bg-[#f2f2f8] w-full px-4 py-3 rounded-lg outline-none"
              />
              <div
                style={{
                  marginTop: -8,
                  display: selectedLeader || !leaderQ ? "none" : "block",
                }}
                className="max-h-[180px] overflow-y-auto py-2"
              >
                {searchResult?.map((leader) => {
                  const name = `${leader.first_name ?? ""} ${
                    leader.last_name ?? ""
                  }`.trim();
                  return (
                    <li
                      onClick={() => handleSelectLeader(leader)}
                      className="block py-2 pl-2"
                      key={leader.id}
                    >
                      {name}
                    </li>
                  );
                })}
              </div>
            </div>
            <div className="flex flex-col gap-2 mb-7">
              <label className="block uppercase text-sm">Network Name</label>
              <input
                ref={inputRef}
                value={name}
                className="bg-[#f2f2f8] w-full px-4 py-3 rounded-lg outline-none"
                placeholder="Enter Network Name"
                onChange={(e) => setName(e.target.value)}
              />
            </div>
            <Button
              disabled={!network || !selectedLeader || !name}
              onClick={handleSubmit}
            >
              Open New Network
            </Button>
          </div>
        </Body>
      </Layout>
    </>
  );
};

export default NewNetwork;
