import Layout from "@/components/templates/page";
import Head from "next/head";
import Header from "@/components/base/header";
import moment from "moment";
import { useState } from "react";
import Lesson from "@/components/base/lesson";
import { useRouter } from "next/router";

export default function ConsolidationDetails() {
  const router = useRouter();

  const handleGoUpOneLevel = () => {
    const currentPathname = router.pathname;
    const parentPathname = currentPathname.split("/").slice(0, -1).join("/");
    router.push(parentPathname);
  };

  return (
    <>
      <Head>
        <title>Disciplr | Conso Details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Layout activeRoute="conso">
        <Header showBackArrrow onBack={handleGoUpOneLevel}>
          <div className="flex w-full justify-between items-center">
            <span>Conso Details</span>
          </div>
        </Header>
      </Layout>
    </>
  );
}

const RelativeDate = (props: { date: any }) => {
  const [original, setShowOriginal] = useState(false);

  if (original)
    return (
      <button className="text-left" onClick={() => setShowOriginal(false)}>
        {moment(props.date).format("LL")}
      </button>
    );

  return (
    <button className="text-left" onClick={() => setShowOriginal(true)}>
      {moment(props.date).fromNow()}
    </button>
  );
};
