import Layout from "@/components/templates/page";
import Head from "next/head";
import Header from "@/components/base/header";
import Body from "@/components/base/body";
import { TbMessageHeart } from "react-icons/tb";
import { PiCrownFill } from "react-icons/pi";

export default function Consolidations() {
  const handleClickConso = () => {
    window.location.href = "/conso/list";
  };

  const handleClickRewards = () => {
    window.location.href = "/conso/rewards";
  };

  return (
    <>
      <Head>
        <title>Disciplr | Consolidations</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Layout activeRoute="conso">
        <Header>
          <div className="flex w-full justify-between items-center">
            <span>Conso</span>
          </div>
        </Header>
        <Body>
          <div className="px-5 flex-col flex gap-4">
            <button onClick={handleClickConso}>
              <div className="bg-[#F9F9F9] rounded-[32px] py-7 px-9">
                <div className="flex items-center gap-5 py-1">
                  <div className="h-[45px] w-[45px] bg-[#E8E8E8] rounded-full flex justify-center items-center text-2xl text-[#FB5D64]">
                    <TbMessageHeart />
                  </div>
                  <header className="font-semibold text-lg text-[#474747]">
                    Consolidations
                  </header>
                </div>
              </div>
            </button>
            <div
              onClick={handleClickRewards}
              className="bg-[#F9F9F9] rounded-[32px] py-7 px-9 cursor-pointer"
            >
              <div className="flex items-center gap-5 py-1 justify-between">
                <div className="flex gap-5">
                  <div className="shrink-0 h-[45px] w-[45px] bg-[#E8E8E8] rounded-full flex justify-center items-center text-2xl text-[#FB5D64]">
                    <PiCrownFill />
                  </div>
                  <div>
                    <header className="font-semibold text-lg text-[#474747]">
                      Rewards
                    </header>
                    <p className="text-[10px]">
                      Earn points when you consolidate.{" "}
                      <a href="#" className="underline text-[#6E7AC5]">
                        Learn more?
                      </a>
                    </p>
                  </div>
                </div>
                <div className="shrink-0 justify-self-end">
                  <span className="text-[10px] font-semibold bg-[#FB5D64] text-white px-4 py-[2px] rounded-full">
                    New
                  </span>
                </div>
              </div>
            </div>
          </div>
        </Body>
      </Layout>
    </>
  );
}
