import Layout from "@/components/templates/page";
import Head from "next/head";
import Header from "@/components/base/header";
import Body from "@/components/base/body";
import { PiCrownFill } from "react-icons/pi";
import { useGetRewards } from "@/lib/queries";

export default function Rewards() {
  const { data } = useGetRewards();

  return (
    <>
      <Head>
        <title>Disciplr | Rewards</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Layout activeRoute="conso" isNavigationHidden>
        <Header showBackArrrow>
          <div className="flex w-full justify-between items-center">
            <span>Rewards</span>
          </div>
        </Header>
        <Body>
          <div className="flex flex-col gap-5">
            <p className="px-7 text-[10px] text-gray-400">You have earned</p>
            <div className="h-[140px] bg-[#6E7AC5] flex justify-center flex-col px-7 text-white">
              <header className="text-xl font-semibold">
                {data?.shekels || 0}
              </header>
              <div className="text-xs text-[10px]">Network shekels</div>
            </div>
            <div className="px-7">
              <header className="font-semibold">Recent Rewards</header>
              <div className="flex flex-col py-5 gap-5">
                <div className="flex gap-7 items-center">
                  <div className="bg-[#F4F4F4] h-[90px] w-[160px] rounded-3xl overflow-hidden relative">
                    <span className="text-[10px] font-semibold bg-[#FB5D64] text-white px-4 py-[2px] rounded-full absolute top-3 left-3">
                      New
                    </span>
                    {/* <img
                      className="w-full h-full object-cover"
                      src="https://images.pexels.com/photos/8383415/pexels-photo-8383415.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
                    /> */}
                  </div>
                  <div>
                    <div className="font-bold text-sm">Devotion Kit</div>
                    <div className="flex items-center gap-2 text-[10px] text-[#828282]">
                      <PiCrownFill />
                      <span>
                        <strong>140</strong> Points
                      </span>
                    </div>
                  </div>
                </div>
                <div className="flex gap-7 items-center">
                  <div className="bg-[#F4F4F4] h-[90px] w-[160px] rounded-3xl overflow-hidden relative">
                    <span className="text-[10px] font-semibold bg-[#6E7AC5] text-white px-4 py-[2px] rounded-full absolute top-3 left-3">
                      Soon
                    </span>
                    {/* <img
                      className="w-full h-full object-cover"
                      src="https://images.pexels.com/photos/6565759/pexels-photo-6565759.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
                    /> */}
                  </div>
                  <div>
                    <div className="font-bold text-sm">Conso Booklet</div>
                    <div className="flex items-center gap-2 text-[10px] text-[#828282]">
                      <PiCrownFill />
                      <span>
                        <strong>140</strong> Points
                      </span>
                    </div>
                  </div>
                </div>
                <div className="flex gap-7 items-center">
                  <div className="bg-[#F4F4F4] h-[90px] w-[160px] rounded-3xl relative">
                    {/* <img
                      className="w-full h-full object-cover"
                      src="https://images.pexels.com/photos/5199805/pexels-photo-5199805.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
                    /> */}
                  </div>
                  <div>
                    <div className="font-bold text-sm">Bible</div>
                    <div className="flex items-center gap-2 text-[10px] text-[#828282]">
                      <PiCrownFill />
                      <span>
                        <strong>140</strong> Points
                      </span>
                    </div>
                  </div>
                </div>
                <div className="flex gap-7 items-center">
                  <div className="bg-[#F4F4F4] h-[90px] w-[160px] rounded-3xl overflow-hidden">
                    {/* <img
                      className="w-full h-full object-cover"
                      src="https://images.pexels.com/photos/236111/pexels-photo-236111.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
                    /> */}
                  </div>
                  <div>
                    <div className="font-bold text-sm">Notebook</div>
                    <div className="flex items-center gap-2 text-[10px] text-[#828282]">
                      <PiCrownFill />
                      <span>
                        <strong>140</strong> Points
                      </span>
                    </div>
                  </div>
                </div>
                <div className="flex gap-7 items-center">
                  <div className="bg-[#F4F4F4] h-[90px] w-[160px] rounded-3xl" />
                  <div>
                    <div className="font-bold text-sm">Ballpen</div>
                    <div className="flex items-center gap-2 text-[10px] text-[#828282]">
                      <PiCrownFill />
                      <span>
                        <strong>140</strong> Points
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </Body>
      </Layout>
    </>
  );
}
