import Layout from "@/components/templates/page";
import Head from "next/head";
import Image from "next/image";

export default function Home() {

    return (
        <>
        <Head>
            <title>Disciplr</title>
            <meta name="description" content="Generated by create next app" />        
            <meta name="viewport" content="width=device-width, initial-scale=1" />     
        </Head>

        <main className="text-center text-grey-900 mb-10">

            <div className="bg-[#6e7ac5]">
                <h1>DISCPLR</h1>
            </div>

        <nav className= "mt-2">
            <aside className="float-left">
            <Image src="/disciplr-logo.png" alt="disciplr" width="50" height="50"/>
            </aside>
            <div className="float-right">
                <ul>
                    <li className="display inline mr-2"><a href="#">About Us</a></li>
                    <li className="display inline mr-2"><a href="#">Login</a></li>
                    <button className="mt-2 bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 hover:bg-gradient-to-r from-indigo-700 via-purple-700 to-pink-700 px-4 py-1 rounded-lg mr-2">Get Started</button>             
                </ul>
            </div>
        </nav>

    
        <div className= "mt-20 py-20"> 
            <p className="font-bold text-5xl opacity-70">Your Ultimate Network</p>
            <p className="font-bold text-5xl opacity-70">Management Solution!</p>
            <p className="opacity-60 mt-10">Discplr streamlines network management with powerful</p>
            <p className="opacity-60 mb-10">features for your organizaion</p>
            <button className="bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 hover:bg-gradient-to-r from-indigo-700 via-purple-700 to-pink-700 text-center px-10 py-3 rounded-lg">Get Started</button>
        </div>
    

        
        <div>
            <p className="font-bold text-5xl opacity-70 mt-10 py-20">Try Discplr for free</p>
        </div>
        

        
        <div>
            <input className="mt-40 px-8 py-3 rounded-lg mr-2" type="email" name="email" id="email" placeholder="Email"></input>
        </div>
        <div>
            <input className="mt-4 px-8 py-3 rounded-lg mr-2" type="Password" name="Passwod" id="Password" placeholder="Password"></input>
        </div>
        <div>
            <button className="mt-7 bg-purple-500 hover:bg-purple-700 px-6 py-3 rounded-lg mr-2">Create Account</button>
        </div>
        

        
        <div>
            <p className=" opacity-60 mt-7 mb-4">By clicking "Create account" or "Sign in with Google", you agree to the our <u><a href="#">Privacy Policy.</a></u></p>
            <p className="font-bold opacity-60 mt-4 mb-4">Already have an account?<span className="text-violet-500"><a href="#"> Log in</a></span></p>
        </div>
        
        <div className= "mt-20 py-20 px-3"> 
                <p className="font-bold text-5xl opacity-70">Streamline, Centralize, &</p>
                <p className="font-bold text-5xl opacity-70">Empower Your Network</p>
                <p className="opacity-60 mt-5">Discplr, the all-in-one platform designed to streamline your</p>
                <p className="opacity-60">network management experience. Whether you're a large or</p>
                <p className="opacity-60">small organization, Discplr offers a range of powerful features to</p>
                <p className="opacity-60">enhance your network's efficiency and connectivity.</p>
            </div>

        <div className="flex justify-center md:justify-start lg:justify-start ">
            <div className=" w-full mx-5 lg:text-left lg:w-2/5 md:w-2/5">
                <p className="font-bold text-3xl opacity-70 text-center lg:text-left md:text-left ">Take control of your network with ease.</p>
                <p className="opacity-60 text-center lg:text-left md:text-left">
                    Discplr, the all-in-one platform designed to streamline your
                    network management experience. Whether you're a large or
                    small organization, Discplr offers a range of powerful features to
                    enhance your network's efficiency and connectivity.
                </p>
                <button className="mt-7 bg-purple-500 px-6 py-3 rounded-lg w-full md:w-32 md:float-left  lg:w-32 lg:float-left ">Consolidate</button>
            </div>
        </div>

        <div className="flex sm:justify-center md:justify-end lg:justify-end">
            <div className=" w-full mt-10 mx-5 text-cemter mb-20 lg:w-2/5 md:w-2/5">
                <p className="font-bold text-3xl opacity-70 text-center lg:text-right md:text-right">Empower your team.</p>
                <p className="opacity-60 text-center lg:text-right md:text-right">
                    Simplify your network by consolidating member
                    information. <b>Disciplr</b> enables you to centralize and
                    update member profiles, ensuring accurate and
                    up-to-date data across your entire network.
                </p>
                <button className="mt-7 bg-purple-500 px-6 py-3 rounded-lg w-full md:w-32 md:float-right  lg:w-32 lg:float-right">Consolidate</button>
            </div>
        </div>

        <div className="flex justify-center md:justify-start lg:justify-start ">
            <div className=" w-full mx-5 lg:text-left lg:w-2/5 md:w-2/5">
                <p className="font-bold text-3xl opacity-70 text-center lg:text-left md:text-left ">Take control of your network with ease.</p>
                <p className="opacity-60 text-center lg:text-left md:text-left">
                    Discplr, the all-in-one platform designed to streamline your
                    network management experience. Whether you're a large or
                    small organization, Discplr offers a range of powerful features to
                    enhance your network's efficiency and connectivity.
                </p>
                <button className="mt-7 bg-purple-500 px-6 py-3 rounded-lg w-full md:w-32 md:float-left  lg:w-32 lg:float-left ">Consolidate</button>
            </div>
        </div>

        <div className="flex sm:justify-center md:justify-end lg:justify-end">
            <div className=" w-full mt-10 mx-5 text-cemter mb-20 lg:w-2/5 md:w-2/5">
                <p className="font-bold text-3xl opacity-70 text-center lg:text-right md:text-right">Empower your team.</p>
                <p className="opacity-60 text-center lg:text-right md:text-right">
                    Simplify your network by consolidating member
                    information. <b>Disciplr</b> enables you to centralize and
                    update member profiles, ensuring accurate and
                    up-to-date data across your entire network.
                </p>
                <button className="mt-7 bg-purple-500 px-6 py-3 rounded-lg w-full md:w-32 md:float-right  lg:w-32 lg:float-right">Consolidate</button>
            </div>
        </div>

        </main>
        
        </>
    );
}
