import Header from "@/components/base/header";
import Layout from "@/components/templates/page";
import Head from "next/head";
import { useRouter } from "next/router";
import Body from "@/components/base/body";
import BreadCrumbs from "@/components/modules/breadcrumbs";
import { useGetEvent } from "@/lib/queries";
import Link from "next/link";
import { events } from "./create";
import { useEffect, useState } from "react";
import axios from "axios";
import Avatar from "@/components/base/avatar";
import MemberBadge from "@/components/base/member-badge/badge";

const EventDetails = () => {
  const router = useRouter();
  const networkId = String(router.query.id);
  const eventId = String(router.query.event_id);

  const { data } = useGetEvent(eventId);

  return (
    <>
      <Head>
        <title>Event</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Layout activeRoute="networks">
        <Header showBackArrrow>
          <div className="flex w-full justify-between items-center">
            {data?.name}
          </div>
        </Header>
        <div className="px-7">
          <BreadCrumbs activePageId="create-event" />
        </div>
        <Body>
          <div className="px-7 py-7">
            <div>
              <header className="flex justify-between">
                <span className="text-[#686777]">PARTICIPANTS</span>
                <Link
                  href={`/networks/${router.query.id}/events/create`}
                  className="text-[#686777]"
                >
                  ADD{" "}
                  <span className="ml-2 px-2 bg-[#6e7ac5] text-white rounded-lg text-lg">
                    +
                  </span>
                </Link>
              </header>
              <div className="flex gap-4 mt-3">
                {data?.event_participants?.map((participant) => (
                  <MemberBadge
                    id={participant.participant_id.id}
                    status={participant.participant_id.status}
                    editable={false}
                    key={participant.id}
                    first_name={participant.participant_id.first_name}
                    last_name={participant.participant_id.last_name}
                  />
                ))}
              </div>
            </div>
          </div>
        </Body>
      </Layout>
    </>
  );
};

export default EventDetails;
