import Header from "@/components/base/header";
import Layout from "@/components/templates/page";
import Head from "next/head";
import { useRouter } from "next/router";
import Body from "@/components/base/body";
import BreadCrumbs from "@/components/modules/breadcrumbs";
import { useGetEvent } from "@/lib/queries";
import Link from "next/link";
import { events } from "./create";

const EventDetails = () => {
  const router = useRouter();
  const networkId = String(router.query.id);
  const eventId = String(router.query.event_id);

  const { data, isLoading } = useGetEvent(eventId);

  console.log(data, isLoading);

  return (
    <>
      <Head>
        <title>Event</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Layout activeRoute="networks">
        <Header showBackArrrow>
          <div className="flex w-full justify-between items-center">
            {data?.name}
          </div>
          {data?.event_type && (
            <span className="text-xs bg-primary text-white py-1 px-4 rounded-full">
              {events[data.event_type]}
            </span>
          )}
        </Header>
        <div className="px-7">
          <BreadCrumbs activePageId="create-event" />
        </div>
        <Body>
          <div className="px-7 py-7">
            <div>
              <header className="flex justify-between">
                <span className="text-[#686777]">PARTICIPANTS</span>
                <Link
                  href={`/networks/${router.query.id}/events/create`}
                  className="text-[#686777]"
                >
                  ADD{" "}
                  <span className="ml-2 px-2 bg-[#6e7ac5] text-white rounded-lg text-lg">
                    +
                  </span>
                </Link>
              </header>
            </div>
          </div>
        </Body>
      </Layout>
    </>
  );
};

export default EventDetails;
