import Calendar from "@/components/modules/calendar";

import Header from "@/components/base/header";
import Layout from "@/components/templates/page";
import { useGetEvents, useGetNetworkDetails } from "@/lib/queries";
import Head from "next/head";
import { useRouter } from "next/router";
import Body from "@/components/base/body";
import DatePicker, { months } from "@/components/modules/datepicker";
import { useEffect, useState } from "react";
import BreadCrumbs from "@/components/modules/breadcrumbs";
import { store } from "@/lib/models";

const Events = () => {
  const router = useRouter();
  const { data: network } = useGetNetworkDetails(String(router.query.id));
  const [showDatePicker, setShowDatePicker] = useState(false);
  const [month, setMonth] = useState(() => new Date().getMonth());
  const [year, setYear] = useState(() => new Date().getFullYear());

  const date = new Date(year, month, 1);

  const { data, isLoading, isError } = useGetEvents({
    network_id: String(router.query.id),
    type: ["CELLGROUP", "CLOSED_CELL", "CONSOLIDATION", "PID"],
    date,
  });

  useEffect(() => {
    if (network?.id) {
      store.dispatch.BreadCrumbs.addPage({
        id: "network-events",
        title: network.name + " Events",
        url: window.origin + router.asPath,
      });
    }
  }, [network, router]);

  return (
    <>
      <DatePicker
        includeDate={false}
        isVisible={showDatePicker}
        onClose={() => setShowDatePicker(false)}
        onConfirm={(value) => {
          setMonth(value.monthIndex);
          setYear(value.year);
        }}
      />
      <Head>
        <title>Disciplr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Layout activeRoute="networks">
        <Header showBackArrrow onBack={() => router.back()}>
          <div className="flex w-full justify-between items-center">
            <span className="whitespace-nowrap overflow-hidden text-ellipsis">
              {network?.name} Events
            </span>
          </div>
        </Header>
        <Body>
          <div className="px-7">
            <BreadCrumbs activePageId="network-events" />
          </div>
          <div className="text-right text-[#6e7ac5] text-lg mb-7 pr-10">
            <button
              onClick={() => setShowDatePicker(true)}
              className="border-b border-[#d0d5f6] "
            >
              {months[month]} {year}
            </button>
          </div>
          <section className="px-7">
            <Calendar year={year} month={month} />
          </section>
        </Body>
      </Layout>
    </>
  );
};

export default Events;
